baseURL = 'https://hrmnjt.dev'
languageCode = 'en-us'
title = 'hrmnjt.dev::sttp://secure_thought_transfer_protocol'

# Disable taxonomy pages
disableKinds = ['taxonomy', 'term']
disableHugoGeneratorInject = true

# Minification
[minify]
  minifyOutput = true

[permalinks]
  shards = '/:year/:month/:day/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = true
    tabWidth = 2
    style = "monokai-sublime"

[params]
  author = 'hrmnjt'
  description = 'Rough, unpolished thoughts and ideas'

# Output formats
[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML', 'RSS']
